name: samtools_view_keep_unaligned
description: Filter BAM/CRAM/SAM file to keep only unaligned reads
keywords:
  - samtools
  - view
  - bam
  - sam
  - cram
  - filter
  - unaligned
tools:
  - samtools:
      description: Tools for manipulating next-generation sequencing data
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      tool_dev_url: https://github.com/samtools/samtools
      doi: "10.1093/bioinformatics/btp352"
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - input:
      type: file
      description: BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - bam:
      type: file
      description: BAM file containing only unaligned reads
      pattern: "*.{bam}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@ethan-mcq"

