name: deconcatenate
description: Deconcatenates multiple assembly sequences
keywords:
  - deconcatenate
  - assembly
  - fasta
tools:
  - deconcatenate:
      description: A tool to deconcatenate assembly sequences

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - assemblies:
      type: file
      description: Input assembly files
      pattern: "*.{fa,fasta}"
  - approx_size:
      type: value
      description: Approximate size for deconcatenation

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - deconcat:
      type: file
      description: Deconcatenated assembly files
      pattern: "*.deconcat.fasta"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@ethanmcq"